apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: python-app
        image: mayorfaj/pythonflask-app:replaceImageTag
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000




